apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "danl-mcp.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "danl-mcp.labels" . | nindent 4 }}
data:
  lattice.json: {{ .Values.configMap.latticeSpec | quote }}
